//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageLogicLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {

        public Order(int id, string username, DateTime orderDate, string product, int amount, Decimal price)
        {

            this.Id = id;
            this.Username = username;
            this.OrderDate = orderDate;
            this.Product = product;
            this.amount = amount;
            this.price = price;

        }
        public int Id { get; set; }
        public string Username { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Product { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
