//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageLogicLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {

        public User() { }

        public User(int i, string u, string p, string m)
        {
            this.Id = i;
            this.Username = u;
            this.Password = p;
            this.Money = m;

        }
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Money { get; set; }
    }
}
